# Generated by Django 3.0.2 on 2020-01-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(blank=True, max_length=56)),
                ('order_id', models.CharField(max_length=36)),
                ('item_title', models.CharField(max_length=70)),
                ('order_id_6', models.CharField(max_length=12)),
                ('pub_share_pre_fee', models.CharField(max_length=10)),
                ('total_commission_fee', models.CharField(max_length=10)),
                ('tk_status', models.IntegerField()),
            ],
        ),
    ]
