# Generated by Django 3.0.2 on 2020-01-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_auto_20200108_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='openid',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
    ]
