# Generated by Django 3.0.2 on 2020-01-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0003_auto_20200110_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='item_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
