# Generated by Django 3.0.2 on 2020-01-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0004_orders_item_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='tb_paid_time',
            field=models.CharField(default=1, max_length=36),
            preserve_default=False,
        ),
    ]
