# Generated by Django 3.0.2 on 2020-01-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0005_orders_tb_paid_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='settle_up',
            field=models.BooleanField(default=False),
        ),
    ]
