# Generated by Django 3.0.2 on 2020-01-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0006_orders_settle_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='alipay',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='name',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
