# Generated by Django 3.0.2 on 2020-01-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0007_auto_20200110_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='settle_up',
            field=models.BooleanField(default=True),
        ),
    ]
