# Generated by Django 3.0.2 on 2020-01-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0008_auto_20200110_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='settle_up',
            field=models.BooleanField(default=False),
        ),
    ]
