# Generated by Django 3.0.2 on 2020-01-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0009_auto_20200110_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='settle_up',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
