# Generated by Django 3.0.2 on 2020-01-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0011_auto_20200110_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='settle_up',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
